CREATE DATABASE linkDev;

CREATE TABLE user (
    id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
    token VARCHAR(255) UNIQUE
);

CREATE TABLE link (
    userId INT UNSIGNED NOT NULL,
    id INT UNSIGNED PRIMARY KEY NOT NULL AUTO_INCREMENT,
	link TEXT,
	redirect TEXT,
    FOREIGN KEY (userId) REFERENCES user(id)
);

CREATE TABLE view (
    linkId INT UNSIGNED NOT NULL,
    ip VARCHAR(255),
    moment BIGINT UNSIGNED,
    FOREIGN KEY (linkId) REFERENCES link(id)
);